default: &default
  adapter: postgresql
  encoding: utf8
  host: 127.0.0.1
  pool: 5

development:
  <<: *default
  username: emba
  password: secret
  database: todo_list_dev

test:
  <<: *default
  username: emba
  password: secret
  database: todo_list_test

production:
  <<: *default
  username: emba
  password: verymuchmoresecret
  database: todo_list
